server:
  port: 8081

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:h2:mem:paymentdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  kafka:
    bootstrap-servers: 127.0.0.1:9094
  cloud:
    stream:
      kafka:
        binder:
          brokers: 127.0.0.1:9094
          replication-factor: 1
          admin:
            properties:
              request.timeout.ms: 30000
      function:
        definition: paymentRequestConsumer
      bindings:
        paymentRequestConsumer-in-0:
          destination: payment-commands
          group: payment-group
        payment-events-out-0:
          destination: payment-events

logging:
  level:
    org.apache.kafka.clients.NetworkClient: WARN
